#!/usr/bin/env bun
// Reads .claude/skills/blurb/ files and generates src/home-content.ts
// Run: bun scripts/sync-home.ts

import { readFileSync, writeFileSync } from "fs"
import { join } from "path"

const root = join(import.meta.dir, "..")

const skillMd = readFileSync(join(root, ".claude/skills/blurb/SKILL.md"), "utf-8")
const widgetSpecMd = readFileSync(join(root, ".claude/skills/blurb/references/widget-spec.md"), "utf-8")

const out = `// AUTO-GENERATED by scripts/sync-home.ts — do not edit manually
export const SKILL_MD = ${JSON.stringify(skillMd)}
export const WIDGET_SPEC_MD = ${JSON.stringify(widgetSpecMd)}
`

writeFileSync(join(root, "src/home-content.ts"), out)
console.log("wrote src/home-content.ts")
